name: docs_examples
description: Examples used in langchaindart.com documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  langchain: ^0.6.0+1
  langchain_chroma: ^0.2.0+2
  langchain_community: 0.1.0+2
  langchain_google: ^0.3.0+2
  langchain_mistralai: ^0.1.0+2
  langchain_ollama: ^0.1.0+2
  langchain_openai: ^0.5.1+1
