name: docs_examples
description: Examples used in langchaindart.com documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  langchain: ^0.3.0
  langchain_chroma: ^0.1.0+9
  langchain_google: ^0.2.1+2
  langchain_mistralai: ^0.0.1+2
  langchain_ollama: ^0.0.1+3
  langchain_openai: ^0.3.0
