name: langchain_google
description: LangChain.dart integration module for Google (VertexAI, PaLM, Matching Engine, etc.).
version: 0.0.9
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_google
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vertex-ai

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  gcloud: ^0.8.11
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  langchain: ^0.0.14
  meta: ^1.9.1
  tiktoken: ^1.0.3
  uuid: ^4.0.0
  vertex_ai: ^0.0.7+1
  cloud_firestore: ^4.9.3
  fake_cloud_firestore: ^2.4.1+1

dev_dependencies:
  test: ^1.21.0
